apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-capstone-deployment
  labels:
    app: sre-capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-capstone
  template:
    metadata:
      labels:
        app: sre-capstone
    spec:
      containers:
        - name: sre-capstone-mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              cpu: "1"
              memory: "512Mi"

        - name: sre-capstone-prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              cpu: "1"
              memory: "512Mi"

        - name: sre-capstone-kafka
          image: apache/kafka:latest
          ports:
            - containerPort: 9092
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              cpu: "1"
              memory: "512Mi"

        - name: sre-capstone-grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              cpu: "1"
              memory: "512Mi"
