apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-dep
  labels:
    app: my-web-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
        - name: sre-capstone-mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017

        - name: sre-capstone-prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090

        - name: sre-capstone-grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: my-web-app
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  selector:
    app: my-web-app
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: my-web-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000