
# Edited by Alec Ippolito
# Rescouces: 
# https://hub.docker.com/r/docker/compose
# https://hub.docker.com/_/mongo
# https://www.baeldung.com/ops/kafka-docker-setup

services:
  # Zookeeper service configuration
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: sre-capstone-zookeeper   
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    restart: always

  # Kafka service configuration
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: sre-capstone-kafka 
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: always

  # MongoDB service configuration
  mongodb:
    image: mongo:5.0
    container_name: sre-capstone-mongodb  
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mydb
    networks:
      - my_network
    restart: always

volumes:
  mongodb_data:

networks:
  my_network:
    driver: bridge
