#edited by Alec Ippolito and Max Benko
#Rescouces: 
#https://hub.docker.com/r/docker/compose
#https://hub.docker.com/_/mongo
#https://hub.docker.com/r/apache/kafka


services:
  #Apache Kafka service configuration
  kafka:
    image: apache/kafka:latest
    container_name: sre-capstone-kafka
    ports:
      - "9092:9092"  

  #MongoDB service configuration
  mongodb:
    image: mongo:latest
    container_name: sre-capstone-mongodb
    restart: always
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
