#edited by Alec Ippolito and Max Benko

#https://hub.docker.com/r/docker/compose
#https://hub.docker.com/_/mongo
#https://hub.docker.com/r/apache/kafka

services:
  # Apache Kafka service configuration
  kafka:
    image: apache/kafka:latest
    container_name: sre-capstone-kafka
    ports:
      - "9092:9092"  

  # MongoDB service configuration
  mongodb:
    image: mongo:latest
    container_name: sre-capstone-mongodb
    restart: always
    ports:
      - "27017:27017"

  # Prometheus service configuration
  prometheus:
    image: prom/prometheus:latest
    container_name: sre-capstone-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml

  # Grafana service configuration
  grafana:
    image: grafana/grafana:latest
    container_name: sre-capstone-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

    volumes:
      - ./grafana_data:/var/lib/grafana
volumes:
  mongodb_data:
  grafana_data: