apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: apache/kafka:latest
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service:2181"  # Corrected to use the Zookeeper service name
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://$(POD_NAME).kafka:9092"
            - name: KAFKA_LOG_DIRS
              value: "/var/lib/kafka/data"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT"
            - name: KAFKA_LISTENER_NAME_PLAINTEXT
              value: "PLAINTEXT"
            - name: KAFKA_LISTENER_PORT_PLAINTEXT
              value: "9092"
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
          command:
            - sh
            - -c
            - |
              echo "Starting Kafka with Zookeeper connection string: zookeeper-service:2181"
              export POD_NAME=$(hostname)
              export KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://$POD_NAME.kafka:9092"
              echo "Starting Kafka with advertised listeners: $KAFKA_ADVERTISED_LISTENERS"
              export BROKER_ID=$(echo ${POD_NAME##*-})
              echo "Starting Kafka with broker ID $BROKER_ID"
              export KAFKA_BROKER_ID=$BROKER_ID
              # Explicitly set the zookeeper.connect in the start command
              sed -i 's/^zookeeper.connect=.*/zookeeper.connect=zookeeper-service:2181/' /opt/kafka/config/server.properties
              /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092