global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']

  - job_name: 'kafka'
    static_configs:
      - targets: ['sre-capstone-kafka-exporter:9308']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090'] 
