# Prometheus configuration
global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-jmx-exporter:9308']
      
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 

  - job_name: 'docker_services'
    static_configs:
      - targets:
          - 'kafka:9092' 
          - 'mongodb:27017'  