name: Docker Compose with Tests Action
 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: adambirds/docker-compose-action@v1.5.0
      with:
        compose-file: "docker-compose.yaml"
